-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "swapsmart"."chat" add column "messageRead" bool
--  not null default 'false';
