-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- DROP TRIGGER IF EXISTS update_unread_messages_count ON swapsmart.chat;
--
-- DROP FUNCTION IF EXISTS swapsmart.update_unread_msg_count;
