-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE FUNCTION swapsmart.update_unread_msg_count()
--     RETURNS trigger AS $BODY$
--     BEGIN
--         INSERT INTO swapsmart.unread_messages_count
--         VALUES (NEW."senderID", NEW."receiverID", 1);
--     RETURN NEW;
--     END;
--     $BODY$ LANGUAGE plpgsql;
--
--
--
--
-- CREATE TRIGGER update_unread_messages_count
--     AFTER INSERT ON swapsmart.chat
--     FOR EACH ROW EXECUTE PROCEDURE
--     swapsmart.update_unread_msg_count();
